openapi: 3.0.0
info:
  title: GA4GH Service Registry API Specification
  version: 1.0.0
  description: 'More information on [GitHub](https://github.com/ga4gh-discovery/ga4gh-service-registry/).'
  license:
    name: Apache 2.0
    url: 'https://raw.githubusercontent.com/ga4gh-discovery/ga4gh-service-registry/develop/LICENSE'
  contact:
    name: GA4GH Discovery Networks Team
    email: ga4gh-discovery-networks@ga4gh.org
paths:
  /services:
    get:
      tags:
        - services
      summary: Get page of services
      parameters:
        - name: authorization
          in: header
          description: The auth token
          required: true
          schema:
            type: string
        - name: page
          in: query
          description: Page token
          required: false
          schema:
            type: string
            example: 'NDMyNzQyODI3OTQw'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                properties:
                  content:
                    type: array
                    items:
                      $ref: '#/components/schemas/Service'
                  pagination:
                    $ref: '#/components/schemas/Pagination'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '500':
          $ref: '#/components/responses/ServerError'
  /services/types:
    get:
      tags:
        - services
      summary: List known service types
      parameters:
        - name: authorization
          in: header
          description: The auth token
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ServiceType'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '500':
          $ref: '#/components/responses/ServerError'
  '/services/{serviceId}':
    get:
      tags:
        - services
      summary: Get service specified by UUID
      parameters:
        - name: serviceId
          in: path
          description: Service identifier
          required: true
          schema:
            type: string
            format: uuid
        - name: authorization
          in: header
          description: The auth token
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Service'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '500':
          $ref: '#/components/responses/ServerError'
components:
  responses:
    NotFound:
      description: Not found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    Unauthorized:
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    Forbidden:
      description: Forbidden
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    ServerError:
      description: Server error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
  schemas:
    Pagination:
      type: object
      properties:
        previousPage:
          type: string
          format: uri
          example: 'https://ga4gh-example-service.com?page=dXNlcjpVMEc5V0ZYTlo'
        nextPage:
          type: string
          format: uri
          example: 'https://ga4gh-example-service.com?page=NDMyNzQyODI3OTQw'
    ServiceType:
      type: string
      description: Indicates the type of the service.
      example: 'BEACON'
    Service:
      type: object
      description: Web server as a service
      properties:
        id:
          type: string
          format: uuid
          description: An identifier (UUID) unique to this service.
          example: '8087d255-1e38-45b6-a5ba-31e2bb50bdd3'
        name:
          type: string
          description: Name of service. It is recommended to be unique and unambiguous.
          example: 'GA4GH Service'
        url:
          type: string
          description: URL of the service (RFC 3986 format).
          example: 'https://foobar.com'
        type:
          $ref: '#/components/schemas/ServiceType'
        createdAt:
          type: string
          format: date-time
          description: Timestamp of service creation in RFC 3339.
          example: '2019-06-04T12:58:19Z'
        updatedAt:
          type: string
          format: date-time
          description: Timestamp of service modification in RFC 3339.
          example: '2019-06-04T12:58:19Z'
        contactUrl:
          type: string
          description: URL of the contact for the host/maintainer of this service, e.g. a link to a contact form (RFC 3986 format), or an email (RFC 2368 format).
          example: 'mailto:support@example.com'
        description:
          type: string
          description: A human readable general description of this service.
        metadata:
          type: object
          additionalProperties:
            type: string
          description: >-
            A set of key-value pairs that represent metadata specific to this
            service.
    Error:
      type: object
      properties:
        code:
          type: integer
          description: HTTP status code
          example: '400'
        message:
          type: string
          description: Description of the error or information.
          example: 'Bad request'
        timestamp:
          type: string
          format: date-time
          description: Timestamp of service modification in RFC 3339.
          example: '2019-06-04T12:58:19Z'
        errors:
          type: array
          items:
            type: object
            properties:
              code:
                type: string
                description: Code
                example: 'IllegalArgumentException'
              message:
                type: string
                description: Description of the error or information.
                example: 'Argument x must be greater than zero'