swagger: '2.0'
info:
  description: GA4GH service registry
  version: 1.0.0
  title: GA4GH Service Registry
  termsOfService: TBD
  contact:
    name: OICR
  license:
    name: GA4GH Service Registry
basePath: /api/v1
paths:
  /services:
    get:
      tags:
        - services
      summary: Retrieve a list of service nodes (e.g., Beacon node, GA4GH DOS node )
      description: >-
        Provide a collection of service nodes.
      operationId: get_nodes
      produces:
        - application/json
      parameters:
        - name: Authorization
          in: header
          description: The auth token
          type: string
          required: true
        - name: query
          in: query
          description: A keyword to search in the fields of service nodes.
          type: string
          required: false
        - name: page_token
          in: query
          description: Page token to identify the record to start retrieval from.
          type: string
          required: false
        - name: page_size
          in: query
          description: The number of entries to be retrieved.
          type: integer
          required: false
      responses:
        '200':
          description: Return service nodes details.
          schema:
            type: array
            items:
              $ref: '#/definitions/Service'
        '400':
          description: >-
            Indicates that the server could not understand the request. This is
            not the same as 422 which indicates a validation error.
          schema:
            $ref: '#/definitions/ErrorDataResponse'
        '401':
          description: >-
            Unauthorized.  This will be returned when no authentication
            information is provided.
          schema:
            $ref: '#/definitions/ErrorDataResponse'
        '403':
          description: >-
            The principal associated with the request does not have sufficient
            rights to perform this operation on the requested resource.
          schema:
            $ref: '#/definitions/ErrorDataResponse'
        '422':
          description: >-
            The request was syntactically correct but was not semantically
            correct. Usually indicating a validation problem.
          schema:
            $ref: '#/definitions/ErrorDataResponse'
        '500':
          description: Internal Server Error.
          schema:
            $ref: '#/definitions/ErrorDataResponse'
    post:
      tags:
        - services
      summary: Create a service node (e.g., Beacon node, GA4GH DOS node etc.)
      description: >-
        Add/Create a service node, owned by the user.
      operationId: create_node
      produces:
        - application/json
      parameters:
        - name: Authorization
          in: header
          description: The auth token
          type: string
          required: true
        - name: request-body
          in: body
          description: 'Service node creation request'
          required: true
          schema:
            $ref: '#/definitions/ServiceCreationRequest'
      responses:
        '201':
          description: Return the newly created service node details.
          schema:
            $ref: '#/definitions/Service'
        '400':
          description: >-
            Indicates that the server could not understand the request. This is
            not the same as 422 which indicates a validation error.
          schema:
            $ref: '#/definitions/ErrorDataResponse'
        '401':
          description: >-
            Unauthorized.  This will be returned when no authentication
            information is provided.
          schema:
            $ref: '#/definitions/ErrorDataResponse'
        '403':
          description: >-
            The principal associated with the request does not have sufficient
            rights to perform this operation on the requested resource.
          schema:
            $ref: '#/definitions/ErrorDataResponse'
        '422':
          description: >-
            The request was syntactically correct but was not semantically
            correct. Usually indicating a validation problem.
          schema:
            $ref: '#/definitions/ErrorDataResponse'
        '500':
          description: Internal Server Error.
          schema:
            $ref: '#/definitions/ErrorDataResponse'
  /services/{service_id}:
    get:
      tags:
        - services
      summary: Retrieve the information of the service node specified by {service_id}
      description:
        Retrieve the information of the service node specified by {service_id}
      operationId: get_node_by_id
      produces:
        - application/json
      parameters:
        - name: service_id
          in: path
          type: string
          required: true
          description: UUID of the service node to get
        - name: Authorization
          in: header
          description: The auth token
          type: string
          required: true
      responses:
        '200':
          description: Return service nodes details.
          schema:
            $ref: '#/definitions/Service'
        '400':
          description: >-
            Indicates that the server could not understand the request. This is
            not the same as 422 which indicates a validation error.
          schema:
            $ref: '#/definitions/ErrorDataResponse'
        '401':
          description: >-
            Unauthorized.  This will be returned when no authentication
            information is provided.
          schema:
            $ref: '#/definitions/ErrorDataResponse'
        '403':
          description: >-
            The principal associated with the request does not have sufficient
            rights to perform this operation on the requested resource.
          schema:
            $ref: '#/definitions/ErrorDataResponse'
        '404':
          description: The requested resource was not found.
          schema:
            $ref: '#/definitions/ErrorDataResponse'
        '422':
          description: >-
            The request was syntactically correct but was not semantically
            correct. Usually indicating a validation problem.
          schema:
            $ref: '#/definitions/ErrorDataResponse'
        '500':
          description: Internal Server Error.
          schema:
            $ref: '#/definitions/ErrorDataResponse'
    put:
      tags:
        - services
      summary: Update the service node specified by {service_id}
      description: >-
        Update the service node specified by {service_id}
      operationId: update_node
      produces:
        - application/json
      parameters:
        - name: service_id
          in: path
          type: string
          required: true
          description: UUID of the service node to update
        - name: Authorization
          in: header
          description: The auth token
          type: string
          required: true
        - name: request-body
          in: body
          description: 'Service node update request'
          required: true
          schema:
            $ref: '#/definitions/ServiceUpdateRequest'
      responses:
        '200':
          description: Return the newly updated service node details.
          schema:
            $ref: '#/definitions/Service'
        '400':
          description: >-
            Indicates that the server could not understand the request. This is
            not the same as 422 which indicates a validation error.
          schema:
            $ref: '#/definitions/ErrorDataResponse'
        '401':
          description: >-
            Unauthorized.  This will be returned when no authentication
            information is provided.
          schema:
            $ref: '#/definitions/ErrorDataResponse'
        '403':
          description: >-
            The principal associated with the request does not have sufficient
            rights to perform this operation on the requested resource.
          schema:
            $ref: '#/definitions/ErrorDataResponse'
        '404':
          description: The requested resource was not found.
          schema:
            $ref: '#/definitions/ErrorDataResponse'
        '422':
          description: >-
            The request was syntactically correct but was not semantically
            correct. Usually indicating a validation problem.
          schema:
            $ref: '#/definitions/ErrorDataResponse'
        '500':
          description: Internal Server Error.
          schema:
            $ref: '#/definitions/ErrorDataResponse'
    delete:
      tags:
        - services
      summary: Delete the service node specified by {service_id}
      description: >-
        Delete the service node specified by {service_id}
      operationId: delete_node
      produces:
        - application/json
      parameters:
        - name: service_id
          in: path
          type: string
          required: true
          description: UUID of the service node to delete
        - name: Authorization
          in: header
          description: The auth token
          type: string
          required: true
      responses:
        '204':
          description: Indicates success
        '400':
          description: >-
            Indicates that the server could not understand the request. This is
            not the same as 422 which indicates a validation error.
          schema:
            $ref: '#/definitions/ErrorDataResponse'
        '401':
          description: >-
            Unauthorized.  This will be returned when no authentication
            information is provided.
          schema:
            $ref: '#/definitions/ErrorDataResponse'
        '403':
          description: >-
            The principal associated with the request does not have sufficient
            rights to perform this operation on the requested resource.
          schema:
            $ref: '#/definitions/ErrorDataResponse'
        '404':
          description: The requested resource was not found.
          schema:
            $ref: '#/definitions/ErrorDataResponse'
        '422':
          description: >-
            The request was syntactically correct but was not semantically
            correct. Usually indicating a validation problem.
          schema:
            $ref: '#/definitions/ErrorDataResponse'
        '500':
          description: Internal Server Error.
          schema:
            $ref: '#/definitions/ErrorDataResponse'
definitions:
  ServiceCreationRequest:
    type: object
    description: 'The object containing information/metadata for the to-be-created service node.'
    properties:
      url:
        type: string
        description: >-
          REQUIRED
          The http/https address of this service node.
      meta_data:
        type: object
        additionalProperties:
          type: string
        description: >-
          OPTIONAL
          A set of key-value pairs that represent metadata specific to this service node provided by the user
        example:
          data_category: KidsCancer
      name:
        type: string
        description: >-
          OPTIONAL
          The name of the service node to be created
        example: AWS-USE2-DATANODE-1
      aliases:
        type: array
        items:
          type: string
        description: >-
         OPTIONAL
         A list of strings that can be used to find this service node to make it more discoverable.
      description:
        type: string
        description: >-
          OPTIONAL
          A human readable general description of this service node.
      service_type:
        $ref: '#/definitions/ServiceTypeEnum'
    required:
        - url
  ServiceUpdateRequest:
    type: object
    description: 'The object containing information for the to-be-updated service node.'
    properties:
      meta_data:
        type: object
        additionalProperties:
          type: string
        description: >-
          OPTIONAL
          A set of key-value pairs that represent metadata specific to this service node provided by the user
        example:
          data_category: KidsCancer
      name:
        type: string
        description: 'OPTIONAL User specified name for the service node'
        example: AWS-USE2-SERVICENODE-1
      aliases:
        type: array
        items:
          type: string
        description: 'OPTiONAL A list of strings that can be used to find this service node to make it more discoverable.'
      description:
        type: string
        description: >-
          OPTIONAL
          A human readable general description of this service node.
  Service:
    type: object
    title: >-
      Service Node - a server which serves ga4ghDataObjects (e.g., file, API or other resource)
    properties:
      id:
        type: string
        description: >-
          REQUIRED
          An identifier unique to this service node.
      name:
        type: string
        description: >-
          OPTIONAL
          A string that can be optionally used to name a service node.
      url:
        type: string
        description: >-
          REQUIRED
          The url (e.g., http/https address) of this service node.
      meta_data:
        type: object
        additionalProperties:
          type: string
        description: >-
          OPTIONAL
          A set of key-value pairs that represent metadata specific to this service node provided by the user
        example:
          data_category: KidsCancer
      health:
        type: object
        description: The health status of this service.
        properties:
          status:
            type: string
          updatedAt:
            type: string
            format: date-time
      created:
        type: string
        format: date-time
        description: >-
          OPTIONAL
          Timestamp of service node creation/addition in RFC3339.
      description:
        type: string
        description: >-
          OPTIONAL
          A human readable general description of this service node.
      aliases:
        type: array
        items:
          type: string
        title: >-
          OPTIONAL
          A list of strings that can be used to find this service node
          to make it more discoverable.
      service_type:
        $ref: '#/definitions/ServiceTypeEnum'
    required:
      - id
      - url
  ServiceTypeEnum:
    type: string
    description: >
      Indicates the type of the service node (e.g. DOS, BEACON etc.).
      By default, it assumes to be DOS type if not specified.
    enum:
      - DOS
      - BEACON
  Error:
    type: object
    properties:
      code:
        type: string
        example: E422CDNPAYRCPTG001
        description: 'Notification code. For instance, developer could make the first character indicate severity (E,W,F).'
      message:
        type: string
        example: Something is invalid
        description: >-
          Description of the error or information notification. Where the
          response is 2xx, it's a notification with informational details about
          this response.
      uuid:
        type: string
        example: aadde-ddddee-eeeedd-eeeedd
        description: Unique identifier for this notification
      timestamp:
        type: string
        format: date-time
        example: 2017-10-12T20:38:45.408Z
        description: Timestamp of the notification
      metadata:
        type: object
        additionalProperties:
          type: object
        description: Context specific to this area. May not be provided.
  ErrorDataResponse:
    type: object
    properties:
      errors:
        type: array
        items:
          $ref: '#/definitions/Error'